name: Biome - Linter
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  
jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        
      - name: Run Linter
        run: biome ci frontend/src
