name: Biome - formatting
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: write
  pull-requests: write
  
jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        
      - name: Run Formatter
        run: biome format --write frontend/src
        
      - name: Push back to repo
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git commit -am "refactor(biome): :recycle: Refactored formatting with pipeline" || true
      
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
