name: Biome Linter

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Formatter
        run: biome format --write frontend/src
      - name: Push back to repo
        run: |
        git config --global user.name "Dinder Pipeline"
        git config --global user.email "pipeline@dinder.com"
        git add &lt;pathspec&gt; git commit -m "refactor(biome): :recycle: Refactored formatting with pipeline"
        git push
